language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - psql -c 'create user qm with superuser' -U postgres
  - psql -d template1 -c 'create extension hstore;'
  - psql -c 'create database qm_test owner qm' -U postgres
